# Generated by Django 6.0.1 on 2026-03-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_total_dents', models.IntegerField(default=32)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('odontogramme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dents', to='patients.odontogramme')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('type_dent', models.CharField(choices=[('dent_de_lait', 'Dent de lait'), ('dent_mixte', 'Dent mixte'), ('dent_permanente', 'Dent permanente')], default='dent_permanente', max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('anonymise', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('mutuelle', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=20, null=True)),
                ('est_public', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(limit_choices_to={'role': 'CABINET'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='odontogramme',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramme_patient', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='Radiographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radiographies/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiographies', to='consultation.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiographies', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='StatutDent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('sain', 'Sain'), ('carie', 'Carie'), ('plombe', 'Plombé'), ('absente', 'Absente'), ('couronne', 'Couronne'), ('implant', 'Implant'), ('obturee', 'Obturée'), ('fracturee', 'Fracturée'), ('devitalisee', 'Dévitalisée'), ('bridge', 'Bridge')], max_length=50)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuts_dent', to='consultation.consultation')),
                ('dent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='patients.dent')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuts_dent_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
