# Generated by Django 6.0.1 on 2026-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type_dent',
            field=models.CharField(choices=[('dent_permanente', 'Dent permanente')], default='dent_permanente', max_length=50),
        ),
    ]
