# Generated by Django 6.0.1 on 2026-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_type_dent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=20, null=True),
        ),
    ]
