# Generated by Django 6.0.1 on 2026-03-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('raison', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('ABSENT', 'Absent')], default='PREVU', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('cabinet', models.ForeignKey(limit_choices_to={'role': 'CABINET'}, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
