# Generated by Django 6.0.1 on 2026-02-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('patients', '0002_patient_user'),
        ('rendezvous', '0002_rendezvous_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='cabinet.cabinet'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient'),
        ),
    ]
