# Generated by Django 6.0.1 on 2026-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('dentiste', 'Dentiste'), ('assistant', 'Assistant'), ('patient', 'Patient')], default='dentiste', max_length=50),
        ),
    ]
