# Generated by Django 6.0.1 on 2026-03-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_customuser_commune_customuser_district_and_more'),
        ('geographique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='province',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='region',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geographique.quartier'),
        ),
    ]
