# Generated by Django 6.0.1 on 2026-02-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
