# Generated by Django 6.0.1 on 2026-02-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('patients', '0001_initial'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='odontogramme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.odontogramme'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendezvous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendezvous.rendezvous'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='consultation.consultation'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='dent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='patients.dent'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='type_traitement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitements', to='consultation.typetraitement'),
        ),
    ]
