# Generated by Django 6.0.1 on 2026-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetraitement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
