# Generated by Django 6.0.1 on 2026-02-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
        ('consultation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('quantite_actuelle', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='cabinet.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée (Achat)'), ('SORTIE', 'Sortie (Utilisation)')], max_length=10)),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.article')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='consultation.consultation')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_realises', to=settings.AUTH_USER_MODEL)),
                ('traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='consultation.traitement')),
            ],
        ),
    ]
